jobs:
display:
  background_image: https://tetacourse.com/uploads/posts/2020-07/1595211523_1.jpg
jobs:
- name: lab-prep
  plan:
    - get: sdwan-devops
      trigger: true
    - task: lab_prep
      file: git-resource/tasks/aws_deploy/vault_prep.yml

- name: deploy-aws-env
  plan:
    - get: sdwan-devops
    - get: terraform-sdwan
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/sdwan-ubuntu
            tag: 1.0
          type: docker-image
        inputs:
          - name: sdwan-devops
          - name: terraform-sdwan
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              export AWS_PAGER=""
              export NAME=$NAME
              echo $NAME
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              echo "Hello, I am your curatedOCI Build Container"
              echo "I have all the required libraries and packages already installed and I have already pulled your branch onto my container"
              echo "Now I will build your code...."
              chmod a+x sdwan-devops/concourse/ansible.sh
              ./sdwan-devops/concourse/ansible.sh

      task: build-vpc
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))
        NAME: ((az.name))
        VAULT_ADDR: ((vault.addr))
        SSH_TOKEN: ((ssh-token.token))

resource_types:
resources:
  - name: sdwan-devops
    source:
      Username: ((Username))
      branch: ((git-branch))
      email: ((email))
      private_key: ((private_key))
      uri: git@github.com:CiscoDevNet/sdwan-devops.git
    type: git

  - name: terraform-sdwan
    source:
      Username: ((Username))
      branch: ((git-branch))
      email: ((email))
      private_key: ((private_key))
      uri: git@github.com:CiscoDevNet/terraform-sdwan.git
    type: git