vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1
        ip:
          address: 192.133.162.21/28
        tunnel_interface:
        enabled: true
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 192.133.162.17