all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: ios
    netconf_template_os: ios
  children:
    network:
      children:
        internet_routers:
          hosts:
            internet:
        intranet_routers:
          hosts:
            intranet:
        router:
          hosts:
            internet:
            intranet:
    system:
      children:
        intranet_hosts:
          hosts:
            intranet-server:
            site20-host1:
            site30-host1:
        # internet_hosts:
        #   hosts:
    sdwan:
      children:
        sdwan_control:
          children:
            vmanage_hosts:
              hosts:
                dc1-vmanage1:
            vbond_hosts:
              hosts:
                dc1-vbond1:
                dc2-vbond1:
            vsmart_hosts:
              hosts:
                dc1-vsmart1:
                dc2-vsmart1:
                dc3-vsmart1:
        sdwan_edge:
          children:
            dc_sites:
              hosts:
                dc1-r1:
                dc1-r2:
                dc2-r1:
                dc3-r1:                   
            branch_sites:
              hosts:
                site10-r1:
                site10-r2:
                site20-r1:
                site30-r1: