interfaces:
  GigabitEthernet1:
    vrf: Mgmt-intf
    enabled: true
    ip:
      primary: dhcp
  GigabitEthernet2:
    enabled: true
    ip:
      primary: dhcp
  GigabitEthernet3:
    enabled: true
    ip:
      primary: 192.133.178.1/24

# static_routes:
#   global:
#     - network: 0.0.0.0/0
#       fwd_list:
#         - fwd: Null0
#     - network: 172.16.0.0/12
#       fwd_list:
#         - fwd: Null0        
