viptela:
  system_ip: 1.1.254.1
  site_id: 254
  vbond:
    remote: 192.133.162.23
  model: 'vedge-CSR-1000v'
  personality: vedge
  uuid: 'CSR-2596BCF3-0AC2-50F9-DC64-FDCF8CCBB971'
  template:
    name: 'dc-cedge'
    variables:
      'vpn512_interface': GigabitEthernet1
      'vpn0_interface': GigabitEthernet2
      'vpn0_internet_ipv4_address': 192.133.162.50/28
      'vpn0_default_gateway': 192.133.162.49
      'vpn10_interface': GigabitEthernet3  
      'vpn10_ospf_interface': GigabitEthernet3
      'vpn10_ipv4_address': 172.16.4.2/24
      'system_latitude': 35.856360
      'system_longitude': -78.879725
      'system_site_id': 254
      'system_host_name': "{{ inventory_hostname }}"
      'system_system_ip': 1.1.254.1
      'banner_login': "{{ login_banner }}"
      'banner_motd': "Welcome to {{ inventory_hostname }}!"
  gps_location:
    latitude: 35.856360
    longitude: -78.879725