sdwan_system_ip: 1.1.12.1
ansible_host: "{{ sdwan_system_ip }}"
sdwan_site_id: "12"
sdwan_uuid: C1111-8PLTEEAWB-FGL233512BN
sdwan_personality: vedge
sdwan_template:
  name: 'branch-1111'
  variables:
    'vpn512_interface': eth0
    'vpn_if_name_Default_vEdge_DHCP_Tunnel_Interface': GigabitEthernet0/0/0
    'vpn1_interface': GigabitEthernet0/0/1
    'vpn1_ipv4_address': 192.168.12.1/24
    'system_latitude': 37.411343
    'system_longitude': -121.938803
    'system_site_id': "{{ sdwan_site_id }}"
    'system_host_name': "{{ inventory_hostname}}"
    'system_system_ip': "{{ sdwan_system_ip }}"
    'banner_login': You are being monitored.
    'banner_motd': Welcome!
bootstrap_method: pnp
