- name: Activate central policy
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ipaddr('address') }}"
  tags:
    - policy
  tasks:
    - name: Activate central policy
      vmanage_central_policy:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        state: activated
        name: "{{ sdwan_central_policy_name }}"
        wait: yes