- name: Attach Templates
  hosts: sdwan
  connection: local
  gather_facts: no
  roles:
    - ansible-viptela
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_ip: "{{ hostvars[vmanage_host].ansible_host | default(hostvars[vmanage_host].sdwan_transport_ip) }}"
  tasks:
    - name: Attach template to device
      vmanage_device_attachment:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        device: "{{ inventory_hostname }}"
        template: "{{ sdwan_template.name }}"
        variables: "{{ sdwan_template.variables }}"
        wait: yes
        state: "present"
      when: sdwan_template is defined
      async: 90
      poll: 10
      register: attachment_results
      tags:
        - attach
