- name: Attach Templates
  hosts: sdwan:&virl_hosts
  connection: local
  gather_facts: no
  roles:
    - ansible-viptela
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_ip: "{{ hostvars[vmanage_host].ansible_host }}"
    state: present
  tasks:
    - block:
      - name: Attach template to device
        vmanage_device_attachment:
          user: "{{ ansible_user }}"
          host: "{{ vmanage_ip }}"
          password: "{{ ansible_password }}"
          device: "{{ inventory_hostname }}"
          template: "{{ viptela.template.name }}"
          variables: "{{ viptela.template.variables | default(omit) }}"
          wait: yes
          state: "{{ state }}"
        delegate_to: localhost
        when: viptela.template is defined
        register: attachment_results
      when: viptela is defined
      delegate_to: localhost

