- name: Attach Templates
  hosts: "{{ passed | default('sdwan') }}"  
  connection: local
  gather_facts: no
  roles:
    - ansible-viptela
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_ip: "{{ hostvars[vmanage_host].ansible_host | default(hostvars[vmanage_host].sdwan_transport_ip) }}"
  tasks:
    - name: Attach template to device
      vmanage_device_attachment:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ vmanage_pass }}"
        uuid: "{{ sdwan_uuid | default(omit) }}"
        device: "{{ inventory_hostname }}"
        system_ip: "{{ sdwan_system_ip | default(omit) }}"
        site_id: "{{ sdwan_site_id | default(omit) }}"
        template: "{{ sdwan_template.name }}"
        variables: "{{ sdwan_template.variables | default(omit) }}"
        wait: yes
        state: present
      when: sdwan_template is defined
      async: 90
      poll: 10
      register: attachment_results
      tags:
        - attach