- name: Update Blocked Apps
  hosts: localhost
  connection: local
  roles:
    - ansible-viptela
  gather_facts: no
  tasks:
    - set_fact:
        vmanage_host: "{{ groups.vmanage_hosts | first }}"

    - set_fact:
        vmanage_ip: "{{ hostvars[vmanage_host].ansible_host | default(hostvars[vmanage_host].sdwan_transport_ip) }}"

    - name: Update Blocked Apps
      vmanage_policy_list:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        name: "blocked_apps"
        entries:
          - app: "twitter"
          - app: "cbs"
          - app: "facebook"
        type: app
        push: yes
        force: no
      register: policy_list_facts
      until: policy_list_facts is not failed
      retries: 60
      delay: 10