- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ansible-virl
  tags:
    - build
  vars:
    lab_file: "{{ virl_lab }}.yaml"
  tasks:
  - name: Create the lab
    virl_lab:
      host: "{{ virl_host }}"
      user: "{{ virl_username }}"
      password: "{{ virl_password }}"
      lab: "{{ virl_lab }}"
      state: present
      file: "{{ lab_file }}"