- name: Generate day0 configs for control hosts
  hosts: sdwan_control
  connection: local
  gather_facts: no
  tasks:
    - name: Generating day0 config
      set_fact:
        day0_config: "{{ lookup('template', virl_config_template) }}"
      when: virl_config_template is defined

- import_playbook: terraform-apply.yml
  vars:
    sdwan_type: control
