- name: Build Control Plane VMs with Terraform
  hosts: localhost
  connection: local
  tags:
    - terraform
    - control
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Generate Terraform variables file for control plane
      template:
        src: templates/control_tfvars.j2
        dest: terraform-sdwan/vmware/control.tfvars
      tags: 
        - plan

    - name: Terraform Plan
      terraform:
        project_path: 'terraform-sdwan/vmware'
        state: planned
        plan_file: control.tfplan
        workspace: control
        variables_file: control.tfvars
        variables:
          datacenter: "{{ datacenter }}"
          cluster: "{{ cluster }}"
          resource_pool: "{{ resource_pool }}"
          datastore: "{{ datastore }}"
          iso_datastore: "{{ iso_datastore }}"
          iso_path: "{{ iso_path }}"
          vmanage_template: "{{ vmanage_template }}"
          vbond_template: "{{ vbond_template }}"
          vsmart_template: "{{ vsmart_template }}"
          vedge_template: "{{ vedge_template }}"
        force_init: yes
#        backend_config:
#          region: "us-east-1"
#          bucket: "terraform-state-sdwan-jenkins"
#          key: "global/s3/terraform.tfstate"
#          dynamodb_table: "terraform-locks-sdwan-jenkins"
#          encrypt: 1
      tags: plan

    - name: Terraform Apply
      terraform:
        project_path: 'terraform-sdwan/vmware'
        state: present
        plan_file: control.tfplan
        workspace: control
        variables_file: control.tfvars
      tags: apply