- name: Ping hosts
  hosts: localhost
  connection: network_cli
  gather_facts: no
  tasks:
    - ios_ping:
        provider:
          host: "{{ hostvars[item.router].ansible_host }}"
          username: admin
          password: admin
        source: "{{ item.src_ip }}"
        dest: "{{ item.dst_ip }}"
        vrf: "{{ item.vrf }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ ping_tests|default([]) }}"
