- name: Ping hosts
  hosts: sdwan_edge
  connection: local
  gather_facts: no
  roles:
    - ansible-viptela
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_ip: "{{ hostvars[vmanage_host].ansible_host | default(hostvars[vmanage_host].vpn0_ip | ipaddr('address')) }}"
    edge_type: "{{ 'vedge' if hostvars[inventory_hostname].sdwan_model is regex('^vedge-[c0-9]') else 'cedge' }}"
    state: present
  tasks:        
    - block:
      - vmanage_nping:
          user: "{{ vmanage_user }}"
          host: "{{ vmanage_ip }}"
          password: "{{ vmanage_pass }}"
          dst_ip: "{{ ping_dst_ip }}"
          vedge: "{{ ping_vedge }}"
          vpn: "{{ ping_vpn }}"
          count: "{{ ping_count | default(5) }}"
          rapid: no
        register: nping
        delegate_to: localhost
    
      - set_fact:
          ping_tx: "{{ nping.json.packetsTransmitted }}"
          # ping_rx: "{{ nping.json.packetsReceived }}"
          ping_rx: "{{ nping.json.rawOutput | select('search', 'Echo reply') | list | length | default('0') }}"
          ping_loss: "{{ nping.json.lossPercentage }}"
          ping_rtt_min: "{{ nping.json.minRoundTrip }}"
          ping_rtt_max: "{{ nping.json.maxRoundTrip }}"
          ping_rtt_avg: "{{ nping.json.avgRoundTrip }}"
      
      - set_fact:
          ping_loss: "{{ (100 - (100 * (ping_rx|int / ping_tx|int))) | int | string }}%"      
      when: edge_type == 'vedge'

    - block:
      - ios_ping:
          provider:
            host: "{{ hostvars[ping_vedge].ansible_host }}"
            username: admin
            password: admin
          source: "{{ ping_src_ip }}"
          dest: "{{ ping_dst_ip }}"
          vrf: "{{ ping_vpn }}"
          state: "{{ 'present' if ping_pass else 'absent' }}"
        connection: network_cli
        delegate_to: localhost
        register: ping
    
      - set_fact:
          ping_rx: "{{ ping.packets_rx }}"
          ping_tx: "{{ ping.packets_tx }}"
          ping_loss: "{{ ping.packet_loss }}"
          ping_rtt_min: "{{ ping.rtt.min }}"
          ping_rtt_max: "{{ ping.rtt.max }}"
          ping_rtt_avg: "{{ ping.rtt.avg }}"
      when: edge_type == 'cedge'

    - debug:
        msg: "{{ ping_vedge }}(VPN {{ping_vpn}}) => {{ ping_dst_ip }}: {{ ping_rx }}/{{ ping_tx }}, {{ ping_loss }} loss, Pass(actual/expected) {{ actual_result }}/{{ expected_result }}"
      failed_when: actual_result != expected_result
      ignore_errors: False
      vars:
        actual_result: "{{ True if ping_loss != '100%' else False }}"
        expected_result: "{{ ping_pass }}"

    # - include_role:
    #     name: ansible-viptela
    #     tasks_from: ping-test
    #   vars:
    #     ping_dst_ip: "{{ item.dst_ip }}"
    #     ping_src_ip: "{{ item.src_ip | default('') }}"
    #     ping_vedge: "{{ item.vedge }}"
    #     ping_vpn: "{{ item.vpn }}"
    #     ping_pass: "{{ item.pass | default(yes) }}"
    #   loop: "{{ ping_tests | default([]) }}"