- name: Ping hosts
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - sdwan-tests
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ipaddr('address') }}"
    state: present
  tasks:
    - include_role:
        name: sdwan-tests
        tasks_from: ping-test
      vars:
        ping_dst_ip: "{{ item.dst_ip }}"
        ping_src_ip: "{{ item.src_ip | default('') }}"
        ping_vedge: "{{ item.vedge }}"
        ping_vpn: "{{ item.vpn }}"
        ping_pass: "{{ item.pass | default(yes) }}"
      loop: "{{ ping_tests | default([]) }}"
      ignore_errors: yes