- hosts: sdwan
  connection: local
  gather_facts: no
  roles:
    - ansible-virl
    - ansible-viptela
  tags:
    - vmanage
  tasks:

    - name: Delete Certificates
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ sdwan_cert_dir }}/{{ inventory_hostname }}.csr"
        - "{{ sdwan_cert_dir }}/{{ inventory_hostname }}.crt"