- import_playbook: clean-certs.yml
  tags: [control]

- import_playbook: remove-device.yml 
  vars: 
    passed: sdwan_edge
  tags: [edges]

- name: Delete Control Plane VMs
  hosts: localhost
  connection: local
  tags:
    - terraform
    - control
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Check for controls.tfvars file
      stat:
        path: 'terraform-sdwan/vmware/control.tfvars'
      register: control_stat_result

    - name: Terraform Destroy Control Plane
      terraform:
        project_path: 'terraform-sdwan/vmware'
        state: absent
        workspace: control
        variables_file: control.tfvars
      when: control_stat_result.stat.exists == true

- name: Delete Edge VMs
  hosts: localhost
  connection: local
  tags:
    - terraform
    - edges
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Check for edges.tfvars file
      stat:
        path: terraform-sdwan/vmware/edges.tfvars
      register: edges_stat_result

    - name: Terraform Destroy Edges
      terraform:
        project_path: 'terraform-sdwan/vmware'
        state: absent
        workspace: edges
        variables_file: edges.tfvars
        variables:
          vmanage_template: "{{ vmware_vmanage_template }}"
          vbond_template: "{{ vmware_vbond_template }}"
          vsmart_template: "{{ vmware_vsmart_template }}"
          vedge_template: "{{ vmware_vedge_template }}"
          cedge_template: "{{ vmware_cedge_template }}"
      when: edges_stat_result.stat.exists == true