- import_playbook: check-reqs.yml

- name: Wait for vmanage mgmt interface to be available
  hosts: localhost
  connection: local
  tags:
    - check_control
    - check_all
    - control
    - CA
  any_errors_fatal: true
  gather_facts: no
  roles:
    - ansible-virl
  tasks:
    - set_fact:
        vmanage_host: "{{ groups.vmanage_hosts | first }}"

    - name: Wait until the mgmt interface comes up
      virl_lab_facts:
        host: "{{ virl_host }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        lab: "{{ virl_lab }}"
      register: result
      until: result.virl_facts.nodes[vmanage_host].ansible_host
      # when: virl_mgmt_interface is defined
      retries: 12
      delay: 10

    - name: Refresh Inventory
      meta: refresh_inventory   

- import_playbook: check-vmanage.yml

- import_playbook: config-vmanage.yml

- import_playbook: import-templates.yml

# - import_playbook: import-policy.yml

- import_playbook: attach-template.yml passed=vsmart_hosts:&virl_hosts

# - import_playbook: activate-policy.yml