- import_playbook: check-reqs.yml

- name: Wait for vmanage mgmt interface to be available
  hosts: localhost
  connection: local
  roles:
    - ansible-virl
  tags:
    - check_control
    - check_all
    - control
    - CA
  any_errors_fatal: true
  gather_facts: no
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
  tasks:
    - name: Wait until the mgmt interface comes up
      virl_lab_facts:
        host: "{{ virl_host }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        lab: "{{ virl_lab }}"
      register: result
      until: result.virl_facts.nodes[vmanage_host]['ansible_host'] | default(False)
      when: hostvars[vmanage_host].mgmt_interface == 'ansible_host'
      retries: 12
      delay: 10

    - set_fact:
        vmanage_ip: "{{ hostvars[vmanage_host].ansible_host | default(hostvars[vmanage_host].vpn0_ip | ipaddr('address')) }}"

    - debug:
        var: vmanage_ip

- import_playbook: check-vmanage.yml

- import_playbook: config-vmanage.yml

- import_playbook: import-templates.yml
  tags:
    - templates

- import_playbook: import-policy.yml
  tags:
    - policy

- import_playbook: attach-template.yml
  tags:
    - templates
    - attach

- import_playbook: activate-policy.yml
  tags:
    - policy
    - attach
