- import_playbook: check-reqs.yml

- import_playbook: config-system.yml

- import_playbook: config-ca.yml

- import_playbook: check-vmanage.yml

- import_playbook: config-vmanage.yml

- import_playbook: import-templates.yml

- import_playbook: import-policy.yml

- import_playbook: attach-template.yml passed=vsmart_hosts