- name: Copy CA to controllers
  hosts: "{{ passed }}"  
  tags:
    - control
    - debug
  any_errors_fatal: true
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    host_mgmt_interface: "{{ hostvars[inventory_hostname].mgmt_interface | default('ansible_host') }}"
    ansible_host: "{{ hostvars[inventory_hostname][host_mgmt_interface] | ipaddr('address') }}"

  tasks:
    - name: Copy Root CA to controllers
      net_put:
        src: "{{ sdwan_cert_dir }}/myCA.pem"
        dest: /home/admin
      register: copy_results

    - name: Install RootCA
      cli_command:
        command: "request root-cert-chain install /home/admin/myCA.pem"
      register: command_result
      failed_when: "'Failed' in command_result.stdout"