- import_playbook: check-reqs.yml

- import_playbook: config-system.yml passed=sdwan_control

- import_playbook: config-ca.yml passed=vbond_hosts

- import_playbook: config-ca.yml passed=vsmart_hosts

- import_playbook: check-vmanage.yml

- import_playbook: config-vmanage.yml

- import_playbook: import-templates.yml

- import_playbook: import-policy.yml

- import_playbook: attach-template.yml passed=vsmart_hosts