- import_playbook: attach-template.yml
  vars:
    passed: sdwan_edge

- import_playbook: get-bootstrap.yml
  vars:
    passed: sdwan_edge

- name: Start the edge nodes
  hosts: sdwan_edge
  connection: local
  gather_facts: no
  tags:
    - start
    - edge
  tasks:
    - name: Start Node
      cisco.cml.cml_node:
        name: "{{ inventory_hostname }}"
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: started
        image_definition: "{{ cml_image_definition | default(omit) }}"
        node_definition: "{{ cml_node_definition | default(omit) }}"
        config: "{{ day0_config | default(omit) }}"
