- import_playbook: attach-template.yml
  vars:
    passed: sdwan_edge

- import_playbook: get-bootstrap.yml
  vars:
    passed: sdwan_edge

- name: Start the edge nodes
  hosts: sdwan_edge
  connection: local
  gather_facts: no
  tags:
    - start
    - edge
  tasks:
    - name: Start Node
      virl_node:
        name: "{{ inventory_hostname }}"
        host: "{{ virl_host }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        lab: "{{ virl_lab }}"
        state: started
        image_definition: "{{ virl_image_definition | default(omit) }}"
        config: "{{ day0_config | default(omit) }}"
