- name: Build vedge VMs with Terraform
  hosts: localhost
  connection: local
  tags:
    - terraform
    - edges
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Generate Terraform variables file for edges
      template:
        src: templates/edges_tfvars.j2
        dest: terraform-sdwan/vmware/edges.tfvars
      tags: always

    - name: Terraform Plan
      terraform:
        project_path: 'terraform-sdwan/vmware'
        state: planned
        plan_file: edges.tfplan
        workspace: edges
        variables_file: edges.tfvars
        variables:
          datacenter: "{{ datacenter }}"
          cluster: "{{ cluster }}"
          resource_pool: "{{ resource_pool }}"
          datastore: "{{ datastore }}"
          iso_datastore: "{{ iso_datastore }}"
          iso_path: "{{ iso_path }}"
          vmanage_template: "{{ vmanage_template }}"
          vbond_template: "{{ vbond_template }}"
          vsmart_template: "{{ vsmart_template }}"
          vedge_template: "{{ vedge_template }}"        
        force_init: yes
      tags: plan

    - name: Terraform Apply
      terraform:
        project_path: 'terraform-sdwan/vmware'
        state: present
        plan_file: edges.tfplan
        workspace: edges
        variables_file: edges.tfvars
      tags: apply

- import_playbook: attach-template.yml passed=vmware_edges

- import_playbook: config-system.yml passed=vmware_edges

- import_playbook: config-ca.yml passed=vmware_edges

- import_playbook: config-uuid-otp.yml passed=vmware_edges

