- name: Import vManage Policy Lists
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - ansible-viptela
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_ip: "{{ hostvars[vmanage_host].ansible_host }}"
  tags:
    - templates  
  tasks:
    - name: Import feature templates
      vmanage_feature_template:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        state: present
        aggregate: "{{ vmanage_feature_templates }}"
      when: vmanage_feature_templates is defined

    - name: Import device templates
      vmanage_device_template:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        state: present
        aggregate: "{{ vmanage_device_templates }}"
      when: vmanage_device_templates is defined