- name: Update RTBH
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ipaddr('address') }}"  
  tasks:
    - name: Update RTBH
      vmanage_policy_list:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        name: "blocked_apps"
        entries:
          - app: "twitter"
          - app: "cbs"
        type: app
        push: yes
        force: no
      register: policy_list_facts
      until: policy_list_facts is not failed
      retries: 60
      delay: 10