- name: Update RTBH
  hosts: localhost
  connection: local
  roles:
    - ansible-viptela
  gather_facts: no
  tasks:
    - set_fact:
        vmanage_host: "{{ groups.vmanage_hosts | first }}"

    - set_fact:
        vmanage_ip: "{{ hostvars[vmanage_host].ansible_host | default(hostvars[vmanage_host].sdwan_transport_ip) }}"

    - name: Update RTBH
      vmanage_policy_list:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        name: "blocked_prefixes"
        entries:
          - ipPrefix: "1.1.1.1/32"
          - ipPrefix: "2.2.2.2/32"
        type: dataprefix
        push: no
        force: no
      register: policy_list_facts
      delegate_to: localhost