- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ansible-virl
  tasks:
    - virl_lab_facts:
        host: "{{ virl_host }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        lab: "{{ virl_lab }}"
      register: result

    - debug:
        var: result.virl_facts.details
