- name: Wait for vEdge Sync
  hosts: vmanage_hosts
  connection: local
  gather_facts: no
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ipaddr('address') }}"  
  tasks:
    - name: Get device facts
      vmanage_device_facts:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
      register: device_facts
      delegate_to: localhost
      until: (all_vedges | difference(device_facts.vedges | selectattr('configStatusMessage', 'defined') | selectattr('configStatusMessage', 'equalto', 'In Sync') | map(attribute='host-name') | list) | length) == 0
      retries: 60
      delay: 10
      vars:
        all_vedges: "{{ groups.sdwan_edge }}"

    - debug:
        msg: "vEdge in sync: {{ device_facts.vedges | selectattr('configStatusMessage', 'defined') | selectattr('configStatusMessage', 'equalto', 'In Sync') | map(attribute='host-name') | list }}"
