- name: Wait for vEdge Sync
  hosts: vmanage_hosts
  connection: local
  roles:
    - ansible-viptela
  gather_facts: no
  tasks:
    - set_fact:
        vmanage_host: "{{ groups.vmanage_hosts | first }}"

    - set_fact:
        vmanage_ip: "{{ hostvars[vmanage_host].ansible_host | default(hostvars[vmanage_host].sdwan_transport_ip) }}"

    - name: Get device facts
      vmanage_device_facts:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
      register: device_facts
      delegate_to: localhost
      until: (all_vedges | difference(device_facts.vedges | selectattr('configStatusMessage', 'defined') | selectattr('configStatusMessage', 'equalto', 'In Sync') | map(attribute='host-name') | list) | length) == 0
      retries: 60
      delay: 10
      vars:
        all_vedges: "{{ groups.sdwan_edge }}"

    - debug:
        msg: "vEdge in sync: {{ device_facts.vedges | selectattr('configStatusMessage', 'defined') | selectattr('configStatusMessage', 'equalto', 'In Sync') | map(attribute='host-name') | list }}"
