all:
  vars:
    sdwan_vbond: 192.133.179.21
  children:
    sdwan:
      children:
        sdwan_control:
          vars:            
            vpn0_portgroup: cpn-rtp-colab1
            vpn0_netmask: 24
            vpn0_gateway: 192.133.179.1
            vpn512_portgroup: cpn-rtp-colab1
          children:
            vmanage_hosts:
              vars:
                sdwan_personality: vmanage
                sdwan_device_model: vmanage
              hosts:
                username-vmanage1:
                  sdwan_system_ip: 1.1.1.1
                  sdwan_transport_ip: 192.133.179.20
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: 1
            vbond_hosts:
              vars:
                sdwan_personality: vbond
                sdwan_device_model: vbond
              hosts:
                username-vbond1:
                  sdwan_system_ip: 1.1.2.1
                  sdwan_transport_ip: 192.133.179.21
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: 2
            vsmart_hosts:
              vars:
                sdwan_personality: vsmart
                sdwan_device_model: vsmart
              hosts:
                username-vsmart1:
                  sdwan_system_ip: 1.1.3.1
                  sdwan_transport_ip: 192.133.179.22
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: 3         
        sdwan_edge:
          children:
            dc_sites:
              hosts:              
            branch_sites:
              hosts:
                username-vedge1:
                  sdwan_system_ip: 1.1.10.1
                  sdwan_transport_ip: 192.133.179.23
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: "10"
                  sdwan_model: 'vedge-cloud'
                  sdwan_uuid: b1b0c97d-acd9-6df5-19d5-6d8a9923fbfb
                  servicevpn_portgroup: cpn-rtp-colab1
                  sdwan_personality: vedge
                  sdwan_template:
                    name: 'branch-vedge-cloud'
                    variables:
                      'vpn512_interface': eth0
                      'vpn0_interface': ge0/0
                      'vpn0_internet_ipv4_address': "{{ sdwan_transport_ip }}/24"
                      'vpn0_default_gateway': 192.133.179.1
                      'vpn1_interface': ge0/1
                      'vpn1_ipv4_address': 192.168.10.1/24
                      'system_latitude': 37.411343
                      'system_longitude': -121.938803
                      'system_site_id': "{{ sdwan_site_id }}"
                      'system_host_name': "{{ inventory_hostname}}"
                      'system_system_ip': "{{ sdwan_system_ip }}"
                      'banner_login': You are being monitored.
                      'banner_motd': Welcome!
                username-vedge2:
                  sdwan_system_ip: 1.1.11.1
                  sdwan_transport_ip: 192.133.179.24
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: "11"
                  sdwan_model: 'vedge-cloud'
                  sdwan_uuid: 663858cb-b1c6-6cc9-0229-9db8e9b7c6c6
                  servicevpn_portgroup: cpn-rtp-colab1
                  sdwan_personality: vedge
                  sdwan_template:
                    name: 'branch-vedge-cloud'
                    variables:
                      'vpn512_interface': eth0
                      'vpn0_interface': ge0/0
                      'vpn0_internet_ipv4_address': "{{ sdwan_transport_ip }}/24"
                      'vpn0_default_gateway': 192.133.179.1
                      'vpn1_interface': ge0/1
                      'vpn1_ipv4_address': 192.168.21.1/24
                      'system_latitude': 37.411343
                      'system_longitude': -121.938803
                      'system_site_id': "{{ sdwan_site_id }}"
                      'system_host_name': "{{ inventory_hostname}}"
                      'system_system_ip': "{{ sdwan_system_ip }}"
                      'banner_login': You are being monitored.
                      'banner_motd': Welcome!
                username-isr1k1:
                  sdwan_system_ip: 1.1.12.1
                  ansible_host: "{{ sdwan_system_ip }}"
                  sdwan_site_id: "12"
                  sdwan_uuid: C1111-8PLTEEAWB-FGL233512BN
                  sdwan_personality: vedge
                  sdwan_template:
                    name: 'branch-c1111'
                    variables:
                      'vpn512_interface': eth0
                      'vpn_if_name_Default_vEdge_DHCP_Tunnel_Interface': GigabitEthernet0/0/0
                      'vpn1_interface': GigabitEthernet0/0/1
                      'vpn1_ipv4_address': 192.168.22.1/24
                      'system_latitude': 37.411343
                      'system_longitude': -121.938803
                      'system_site_id': "{{ sdwan_site_id }}"
                      'system_host_name': "{{ inventory_hostname}}"
                      'system_system_ip': "{{ sdwan_system_ip }}"
                      'banner_login': You are being monitored.
                      'banner_motd': Welcome!
    environment:
      children:
        vmware:
          vars:
            bootstrap_method: netconf
            vpn0_portgroup: cpn-rtp-colab1
            vpn0_netmask: 24
            vpn0_gateway: 192.133.179.1
            vpn512_portgroup: cpn-rtp-colab1
          hosts:
            username-vedge1:
            username-vedge2:
        physical:
          vars:
            bootstrap_method: pnp
          hosts:
            username-isr1k1:
        virl:
        aws:
