---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/sdwan-ubuntu
    tag: 1.0

inputs:
  - name: input

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  REGION: ((aws.region))
  NAME: ((az.name))
  VAULT_ADDR: ((vault.addr))
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -cex
    - |
      cd input
      ls -la
      chmod a+x aws_vars.sh
      ./aws_vars.sh
      





    
    
    


