---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/sdwan-ubuntu
    tag: 1.0

inputs:
  - name: input

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  REGION: us-west-2
  NAME: us-west-2a
  VAULT_ADDR: http://dev-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -cex
    - |
      cd input
      ls -la
      chmod a+x aws_env_example_pipe.sh
      ./aws_env_example_pipe.sh
      





    
    
    


