vmanage_ping_tests:
#
# Test colo-to-site
#
  - dst_ip: 10.22.3.10
    vedge: east-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 10.23.3.10
    vedge: west-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 10.22.4.10
    vedge: west-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 10.23.4.10
    vedge: west-vedge1
    vpn: 11
    pass: yes
#
# Test site-to-site intra-VPN
#
  - dst_ip: 10.23.3.10
    vedge: site1-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 10.22.3.10
    vedge: site2-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 10.23.4.10
    vedge: site1-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 10.22.4.10
    vedge: site2-vedge1
    vpn: 11
    pass: yes
#
# Test site-to-site inter-VPN
#
  - dst_ip: 10.23.3.10
    vedge: site1-vedge1
    vpn: 11
    pass: no
  - dst_ip: 10.22.3.10
    vedge: site2-vedge1
    vpn: 11
    pass: no
  - dst_ip: 10.23.4.10
    vedge: site1-vedge1
    vpn: 10
    pass: no
  - dst_ip: 10.22.4.10
    vedge: site2-vedge1
    vpn: 10
    pass: no
#
# Test Corp to Internal Services
#
  - dst_ip: 172.20.1.10
    vedge: site1-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 172.20.1.10
    vedge: site2-vedge1
    vpn: 11
    pass: yes
#
# Test Guest to Internal Services
#
  - dst_ip: 172.20.1.10
    vedge: site1-vedge1
    vpn: 10
    pass: no
  - dst_ip: 172.20.1.10
    vedge: site2-vedge1
    vpn: 10
    pass: no
#
# Test to Cirtical External Services
#
  - dst_ip: 172.17.0.10
    vedge: site1-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 172.17.0.10
    vedge: site2-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 172.17.0.10
    vedge: site1-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 172.17.0.10
    vedge: site2-vedge1
    vpn: 11
    pass: yes
