all:
  children:
    network:
      children:
        internet_routers:
          hosts:
            colab-rtr:
        router:
          hosts:
            colab-rtr:
    sdwan:
      children:
        sdwan_control:
          children:
            vmanage_hosts:
              vars:
                sdwan_personality: vmanage
                sdwan_device_model: vmanage
              hosts:
                  cleur-vmanage1:
            vbond_hosts:
              vars:
                sdwan_personality: vbond
                sdwan_device_model: vbond
              hosts:
                cleur-vbond1:
#                cleur-vbond2:
            vsmart_hosts:
              vars:
                sdwan_personality: vsmart
                sdwan_device_model: vsmart
              hosts:
                cleur-vsmart1:
                cleur-vsmart2:        
        sdwan_edge:
          children:
            # physical:
            #   hosts:              
            #     cleur-isr1k1:
            vmware_edges:
              hosts:
                cleur-vedge1:
                cleur-vedge2:
