all:
  vars:
    ansible_network_os: ios
    netconf_template_os: ios
  children:
    network:
      vars:
        cml_image_definition: "{{ csr1000v_image }}"
        cml_node_definition: "{{ csr1000v_nodedef }}"
      children:
        internet_routers:
          hosts:
            internet:
            sp1-rtr1:
            hq-rtr1:
        router:
          hosts:
            internet:
            sp1-rtr1:
            hq-rtr1:
            hq-dc-rtr1:
          children:
            colo_routers:
              hosts:
                hq-rtr1:
