all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: ios
    netconf_template_os: ios
  children:
    network:
      children:
        internet_routers:
          hosts:
            internet:
            sp1-rtr1:
            hq-rtr1:
        router:
          hosts:
            internet:
            sp1-rtr1:
            hq-rtr1:
            hq-dc-rtr1:
          children:
            colo_routers:
              hosts:
                hq-rtr1:
    system:
      children:
        client:
          hosts:
            site1-host1:
            site2-host1:
        public_hosts:
          hosts:
            hq-host1:
            # sp1-host1:
    sdwan:
      children:
        sdwan_control:
          children:
            vmanage_hosts:
              hosts:
                vmanage1:
            vbond_hosts:
              hosts:
                vbond1:
            vsmart_hosts:
              hosts:
                vsmart1:
        sdwan_edge:
          hosts:
            hq-cedge1:
            site1-cedge1:
            site2-vedge1:
            