interfaces:
  GigabitEthernet1:
    vrf: Mgmt-intf
    enabled: true
    ip:
      primary: dhcp
  GigabitEthernet2:
    enabled: true
    ip:
      primary: 10.0.0.13/24
  GigabitEthernet3:
    enabled: true
    ip:
      primary: 10.0.255.5/30

static_routes:
  global:
    - network: 0.0.0.0/0
      fwd_list:
        - fwd: 10.0.0.1
