viptela:
  system_ip: 192.168.255.14
  site_id: 2
  vbond:
    remote: 10.0.0.11
  template:
    name: 'branch-vedge'
    variables:
      'vpn0_internet_ipv4_address': 172.20.0.10/30
      'vpn0_default_gateway': 172.20.0.9
      'vpn1_ipv4_address': 192.168.1.1/24
      'system_latitude': 35.856360
      'system_longitude': -78.879725
      'system_site_id': 2
      'system_host_name': site1-vedge1
      'system_system_ip': 192.168.255.14
      'banner_login': "{{ login_banner }}"
      'banner_motd': Welcome to site1-vedge1!
  gps_location:
    latitude: 35.856360
    longitude: -78.879725