vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: ge0/0
        ip:
          address: 172.21.0.7/24
        tunnel_interface:
        shutdown: false
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 172.21.0.1