all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: ios
    netconf_template_os: ios
  children:
    internet_routers:
      hosts:
        internet:
        sp:
        hq:
    router:
      hosts:
        internet:
        sp:
        hq:
        core:
      children:
        colo_routers:
          hosts:
            hq:
    client:
      hosts:
        host1:
    public_hosts:
      hosts:
        server1:
        service1:
    viptela:
      children:
        viptela_control:
          children:
            vmanage_hosts:
              hosts:
                vmanage1:
            vbond_hosts:
              hosts:
                vbond1:
            vsmart_hosts:
              hosts:
                vsmart1:
        viptela_vedge:
          hosts:
            vedge1:
            vedge-hq: