interfaces:
#  Management0/0:
#    enabled: true
#    # management_only: yes
#    nameif: management
#    ip:
#      primary: dhcp
  GigabitEthernet0/0:
    enabled: true
  GigabitEthernet0/1:
    enabled: true
    nameif: outside
    security_level: 0
    ip:
      primary: 172.20.0.4/24
      standby: 172.20.0.5
  GigabitEthernet0/2:
    enabled: true
    nameif: colo
    security_level: 0
    ip:
      primary: 172.20.1.1/24
      standby: 172.20.1.2
  GigabitEthernet0/3:
    enabled: true
    nameif: cloud
    security_level: 0
    ip:
      primary: 10.20.2.1/24
      standby: 10.20.2.2
  GigabitEthernet0/4:
    enabled: true
    nameif: guest
    security_level: 0
    ip:
      primary: 10.20.3.1/24
      standby: 10.20.3.2
  GigabitEthernet0/5:
    enabled: true
    nameif: corp
    security_level: 0
    ip:
      primary: 10.20.4.1/24
      standby: 10.20.4.2

#failover:
#  role: primary
#  ip: 10.255.255.1/30
#  peer_ip: 10.255.255.2/30
#  interface: GigabitEthernet0/0

static_routes:
  Null0:
    - network: 0.0.0.0/0

nat:
  - inside_interface: corp
    outside_interface: outside
    source_type: dynamic
    source_list: any
  - inside_interface: guest
    outside_interface: outside
    source_type: dynamic
    source_list: any

prefix_lists:
  corp:
    - network: 0.0.0.0/0
      action: permit
    - network: 10.20.2.0/24
      action: permit
    - network: 172.20.1.0/24
      action: permit
  default-only:
    - network: 0.0.0.0/0
      action: permit
  internet:
    - network: 172.20.1.0/24
      action: permit

router:
  bgp:
    id: 65020
    log_neighbor_changes: true
    router_id: 172.20.0.4
    address_family:
      ipv4:
        neighbors:
          - id: 172.20.0.2
            remote_as: 65020
            activate: true
            prefix_lists:
              out: internet
          - id: 10.20.3.3
            remote_as: 65025
            activate: true
            prefix_lists:
              out: default-only
          - id: 10.20.4.3
            remote_as: 65025
            activate: true
            prefix_lists:
              out: corp
#        networks:
#          - network: 172.20.0.0/16
#          - network: 0.0.0.0/0
        redistribute:
          connected:
        auto_summary: no
        synchronization: no
#  ospf:
#    id: 65020
#    router_id: 172.20.0.4
#    default_information_originate: true
#    networks:
#      - network: 172.20.0.0/24
#        area: 0
#      - network: 172.20.1.0/24
#        area: 1
#      - network: 10.20.2.0/24
#        area: 2
#      - network: 10.20.3.0/24
#        area: 10
#      - network: 10.20.4.0/24
#        area: 11
#
#    areas:
#      - number: 1
#        options:
#          - nssa
#          - no-redistribution
#          - default-information-originate
#          - no-summary
#      - number: 2
#        options:
#          - nssa
#          - no-redistribution
#          - default-information-originate
#          - no-summary
#      - number: 3
#        options:
#          - nssa
#          - no-redistribution
#          - default-information-originate
#          - no-summary
#      - number: 10
#        options:
#          - nssa
#          - no-redistribution
#          - default-information-originate
#          - no-summary
#      - number: 11
#        options:
#          - nssa
#          - no-redistribution
#          - default-information-originate
#          - no-summary

dns_interface: management

licensing:
  feature: standard
  throughput: 1G