all:
  vars:
    sdwan_vbond: 192.133.179.14
  children:
    sdwan:
      children:
        sdwan_control:
          vars:            
            vpn0_portgroup: cpn-rtp-colab1
            vpn0_netmask: 24
            vpn0_gateway: 192.133.179.1
            vpn512_portgroup: vpn512
          children:
            vmanage_hosts:
              vars:
                sdwan_personality: vmanage
                sdwan_device_model: vmanage
              hosts:
                cpn-rtp-vmanage1:
                  sdwan_system_ip: 1.1.1.1
                  sdwan_transport_ip: 192.133.179.11
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: 1
            vbond_hosts:
              vars:
                sdwan_personality: vbond
                sdwan_device_model: vbond
              hosts:
                cpn-rtp-vbond1:
                  sdwan_system_ip: 1.1.4.1
                  sdwan_transport_ip: 192.133.179.14
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: 4
            vsmart_hosts:
              vars:
                sdwan_personality: vsmart
                sdwan_device_model: vsmart
              hosts:
                cpn-rtp-vsmart1:
                  sdwan_system_ip: 1.1.2.1
                  sdwan_transport_ip: 192.133.179.12
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: 2  
                cpn-rtp-vsmart2:
                  sdwan_system_ip: 1.1.3.1
                  sdwan_transport_ip: 192.133.179.13
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: 3           
        sdwan_edge:
          children:
            dc_sites:
              hosts:              
            branch_sites:
              hosts:
                cpn-rtp-vedge1:
                  sdwan_system_ip: 1.1.10.1
                  sdwan_transport_ip: 192.133.179.16
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: "10"
                  sdwan_model: 'vedge-cloud'
                  sdwan_uuid: b1b0c97d-acd9-6df5-19d5-6d8a9923fbfb
                  servicevpn_portgroup: site10
                  sdwan_personality: vedge
                  sdwan_template:
                    name: 'branch-vedge-cloud'
                    variables:
                      'vpn512_interface': eth0
                      'vpn0_interface': ge0/0
                      'vpn0_internet_ipv4_address': 192.133.179.16/24
                      'vpn0_default_gateway': 192.133.179.1
                      'vpn1_interface': ge0/1
                      'vpn1_ipv4_address': 192.168.10.1/24
                      'system_latitude': 37.411343
                      'system_longitude': -121.938803
                      'system_site_id': "{{ sdwan_site_id }}"
                      'system_host_name': "{{ inventory_hostname}}"
                      'system_system_ip': "{{ sdwan_system_ip }}"
                      'banner_login': You are being monitored.
                      'banner_motd': Welcome!
                cpn-rtp-vedge2:
                  sdwan_system_ip: 1.1.11.1
                  sdwan_transport_ip: 192.133.179.17
                  ansible_host: "{{ sdwan_transport_ip }}"
                  sdwan_site_id: "11"
                  sdwan_model: 'vedge-cloud'
                  sdwan_uuid: 663858cb-b1c6-6cc9-0229-9db8e9b7c6c6
                  servicevpn_portgroup: site11
                  sdwan_personality: vedge
                  sdwan_template:
                    name: 'branch-vedge-cloud'
                    variables:
                      'vpn512_interface': eth0
                      'vpn0_interface': ge0/0
                      'vpn0_internet_ipv4_address': 192.133.179.17/24
                      'vpn0_default_gateway': 192.133.179.1
                      'vpn1_interface': ge0/1
                      'vpn1_ipv4_address': 192.168.11.1/24
                      'system_latitude': 37.411343
                      'system_longitude': -121.938803
                      'system_site_id': "{{ sdwan_site_id }}"
                      'system_host_name': "{{ inventory_hostname}}"
                      'system_system_ip': "{{ sdwan_system_ip }}"
                      'banner_login': You are being monitored.
                      'banner_motd': Welcome!
                cpn-rtp-isr1k1:
                  sdwan_system_ip: 1.1.12.1
#                  sdwan_transport_ip: 192.133.179.18
                  ansible_host: "{{ sdwan_system_ip }}"
                  sdwan_site_id: "12"
#                  sdwan_model: 'C1111-8PLTEEAW'
                  sdwan_uuid: C1111-8PLTEEAWB-FGL233512BN
                  sdwan_personality: vedge
                  sdwan_template:
                    name: 'branch-c1111'
                    variables:
                      'vpn512_interface': eth0
                      'vpn_if_name_Default_vEdge_DHCP_Tunnel_Interface': GigabitEthernet0/0/0
                      'vpn1_interface': GigabitEthernet0/0/1
                      'vpn1_ipv4_address': 192.168.12.1/24
                      'system_latitude': 37.411343
                      'system_longitude': -121.938803
                      'system_site_id': "{{ sdwan_site_id }}"
                      'system_host_name': "{{ inventory_hostname}}"
                      'system_system_ip': "{{ sdwan_system_ip }}"
                      'banner_login': You are being monitored.
                      'banner_motd': Welcome!
    environment:
      children:
        vmware:
          vars:
            bootstrap_method: netconf
            vpn0_portgroup: cpn-rtp-colab1
            vpn0_netmask: 24
            vpn0_gateway: 192.133.179.1
            vpn512_portgroup: vpn512
          hosts:
            cpn-rtp-vedge1:
            cpn-rtp-vedge2:
        physical:
          vars:
            bootstrap_method: pnp
          hosts:
            cpn-rtp-isr1k1:
        virl:
        aws:
