interfaces:
  GigabitEthernet0/0:
    enabled: true
  GigabitEthernet0/1:
    enabled: true
    nameif: outside
    security_level: 0
    ip:
      primary: 172.21.0.4/24
      standby: 172.21.0.5
  GigabitEthernet0/2:
    enabled: true
    nameif: colo
    security_level: 0
    ip:
      primary: 172.21.1.1/24
      standby: 172.21.1.2
  GigabitEthernet0/3:
    enabled: true
    nameif: cloud
    security_level: 0
    ip:
      primary: 10.21.2.1/24
      standby: 10.21.2.2
  GigabitEthernet0/4:
    enabled: true
    nameif: guest
    security_level: 0
    ip:
      primary: 10.21.3.1/24
      standby: 10.21.3.2
  GigabitEthernet0/5:
    enabled: true
    nameif: corp
    security_level: 0
    ip:
      primary: 10.21.4.1/24
      standby: 10.21.4.2

#failover:
#  role: primary
#  ip: 10.255.255.1/30
#  peer_ip: 10.255.255.2/30
#  interface: GigabitEthernet0/0

static_routes:
  Null0:
    - network: 0.0.0.0/0

nat:
  - inside_interface: corp
    outside_interface: outside
    source_type: dynamic
    source_list: any
  - inside_interface: guest
    outside_interface: outside
    source_type: dynamic
    source_list: any

prefix_lists:
  corp:
    - network: 0.0.0.0/0
      action: permit
    - network: 10.21.2.0/24
      action: permit
    - network: 172.21.1.0/24
      action: permit
  default-only:
    - network: 0.0.0.0/0
      action: permit
  internet:
    - network: 172.21.1.0/24
      action: permit

router:
  bgp:
    id: 65021
    log_neighbor_changes: true
    router_id: 172.21.0.4
    address_family:
      ipv4:
        neighbors:
          - id: 172.21.0.2
            remote_as: 65021
            activate: true
            prefix_lists:
              out: internet
          - id: 10.21.3.3
            remote_as: 65025
            activate: true
            prefix_lists:
              out: default-only
          - id: 10.21.4.3
            remote_as: 65025
            activate: true
            prefix_lists:
              out: corp
#        networks:
#          - network: 172.21.0.0/16
        redistribute:
          connected:
        auto_summary: no
        synchronization: no

dns_interface: management

licensing:
  feature: standard
  throughput: 1G