---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/sdwan-ubuntu
    tag: 1.0

inputs:
  - name: git-cisco-sdwan-devops

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  REGION: us-west-2
  NAME: us-west-2a
  VAULT_ADDR: http://http://vault.cisco-sdwan-labs.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -ce
    - |
      export AWS_PAGER=""
      export Name=$NAME
      echo $NAME
      aws configure set aws_access_key_id $AWS_KEY_ID
      aws configure set aws_secret_access_key $AWS_KEY
      aws configure set default.region $REGION
      aws sts get-caller-identity --query Account --output text
      chmod a+x git-cisco-sdwan-devops/tasks/python/aws_delete/aws_vmanage_3_delete.sh
      git-cisco-sdwan-devops/tasks/python/aws_delete/aws_vmanage_3_delete.sh
    


      