---
FeatureTemplates:
  feature-vpn:
    - templateName: 'CLEUR_VPN0'
      templateDescription: 'VPN Template'
      vpnID:
        globalValue: 0
      name:
        globalValue: 'Transport VPN 0'
      ecmpLayer4:
        globalValue: 'true'
      staticRoutes:
        - prefix:
            variableName: 'static_route'
          nextHops:
            - address:
                variableName: 'next_hop_ip_address'
          optional: true
      deviceType:
        - vEdge
      state: 'present'
    - templateName: 'CLEUR_VPN10'
      templateDescription: 'VPN Template'
      vpnID:
        globalValue: 10
      name:
        globalValue: 'Service VPN 10'
      deviceType:
        - vEdge
      state: 'present'
