---
DeviceTemplate:
  - templateName: 'CLEUR_Device_T'
    templateDescription: 'CLEUR_Device_T'
    deviceType: 'vedge-cloud'
    aaa: 'Factory_Default_AAA_Template'
    bfd-vedge: CLEUR_BFD
    banner: CLEUR_Banner
    logging: CLEUR_Logging
    omp-vedge: Factory_Default_vEdge_OMP_Template
    security-vedge: Factory_Default_vEdge_Security_Template
    system-vedge: CLEUR_System
    vpn-vedge:
      - CLEUR_VPN0:
        - CLEUR_Transport1_DHCP
      - CLEUR_VPN10:
        - CLEUR_Loopback0
      - Factory_Default_vEdge_VPN_512_Template:
        - CLEUR_VPN512_ETH_INT
    state: 'present'
