viptela:
  system_ip: 1.1.10.2
  site_id: 10
  vbond:
    remote: 192.133.162.23
  model: 'vedge-CSR-1000v'
  personality: vedge
  uuid: 'CSR-0EC4EC5C-AA31-5B91-DCBC-C18DAC08E4FA'
  template:
    name: 'branch-cedge'
    variables:
      'vpn512_interface': GigabitEthernet1
      'vpn0_interface': GigabitEthernet2
      'vpn0_internet_ipv4_address': 192.133.162.82/28
      'vpn0_default_gateway': 192.133.162.81
      'vpn10_interface': GigabitEthernet3  
      'vpn10_ospf_interface': GigabitEthernet3
      'vpn10_ipv4_address': 172.16.11.1/24
      'system_latitude': 35.856360
      'system_longitude': -78.879725
      'system_site_id': 10
      'system_host_name': "{{ inventory_hostname }}"
      'system_system_ip': 1.1.10.2
      'banner_login': "{{ login_banner }}"
      'banner_motd': "Welcome to {{ inventory_hostname }}!"
  gps_location:
    latitude: 35.856360
    longitude: -78.879725