- name: Detach Template
  hosts: "{{ passed | default('sdwan') }}"  
  connection: local
  gather_facts: no
  vars:
    ansible_async_dir: "/tmp/ansible_async"
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ansible.utils.ipaddr('address') }}"
  tasks:

    - name: Detach template from device
      vmanage_device_attachment:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        device: "{{ inventory_hostname }}"
        wait: yes
        state: absent
      when: sdwan_template is defined
      async: 90
      poll: 10
      register: attachment_results
