- name: Export vManage Policy Lists
  hosts: localhost
  connection: local
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ansible.utils.ipaddr('address') }}"
    file: vmanage-policy.yml
  environment: "{{ proxy_env }}"
  gather_facts: no
  tasks:   
    - vmanage_export_policy:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ vmanage_pass }}"
        file: "{{ file }}"
