- name: Import vManage Feature/Device Templates
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ansible.utils.ipaddr('address') }}"
  environment: "{{ proxy_env }}"
  tasks:
    - vmanage_template_import:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ vmanage_pass }}"
        file: "{{ vmanage_templates_file }}"
      when: vmanage_templates_file is defined
