interfaces:
  GigabitEthernet1:
    vrf: Mgmt-intf
    enabled: true
    ip:
      primary: dhcp
  GigabitEthernet2:
    enabled: true
    ip:
      primary: 172.16.1.1/24
  GigabitEthernet3:
    enabled: true
    ip:
      primary: 172.16.2.1/24
  GigabitEthernet4:
    enabled: true
    ip:
      primary: 172.16.3.1/24
  GigabitEthernet5:
    enabled: true
    ip:
      primary: 172.16.4.1/24
  GigabitEthernet6:
    enabled: true
    ip:
      primary: 172.16.5.1/24

router:
  ospf:
    id: 10
    router_id: 172.16.1.1
#    default_information_originate: true
    networks:
      - network: 172.16.1.0/24
        area: 0
      - network: 172.16.2.0/24
        area: 0
      - network: 172.16.3.0/24
        area: 0
      - network: 172.16.4.0/24
        area: 0
      - network: 172.16.5.0/24
        area: 0

# static_routes:
#   global:
#     - network: 0.0.0.0/0
#       fwd_list:
#         - fwd: Null0
#     - network: 172.16.0.0/12
#       fwd_list:
#         - fwd: Null0        

# router:
#   bgp:
#     id: 65000
#     log_neighbor_changes: true
#     router_id: 172.20.0.5
#     neighbors:
#       - id: 172.20.0.6
#         remote_as: 65001
#       - id: 172.20.0.18
#         remote_as: 65002
#     address_family:
#       global:
#         ipv4:
#           neighbors:
#             - id: 172.20.0.6
#               activate: true
#             - id: 172.20.0.18
#               activate: true
#           networks:
#             - network: 172.16.0.0/12
