vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: ge0/0
        ip:
          address: 172.20.0.14/30
        tunnel_interface:
        enabled: true
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 172.20.0.13