vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1
        ip:
          address: 192.133.162.35/28
        tunnel_interface:
          allow_service:
            - all
        enabled: yes
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 192.133.162.33