sdwan_system_ip: 1.1.11.1
sdwan_transport_ip: 192.133.179.27
vpn0_netmask: 24
vpn0_gateway: 192.133.179.1
ansible_host: "{{ sdwan_transport_ip }}"
sdwan_site_id: 11
sdwan_model: 'vedge-cloud'
sdwan_uuid: a6bed286-74e3-290f-95cb-2aa2d77e4366
sdwan_personality: vedge
sdwan_template:
  name: 'branch-vedge-cloud'
  variables:
    'vpn512_interface': eth0
    'vpn0_interface': ge0/0
    'vpn0_internet_ipv4_address': "{{ sdwan_transport_ip }}/{{ vpn0_netmask }}"
    'vpn0_default_gateway': "{{ vpn0_gateway }}"
    'vpn1_interface': ge0/1
    'vpn1_ipv4_address': 192.168.11.1/24
    'system_latitude': 37.411343
    'system_longitude': -121.938803
    'system_site_id': "{{ sdwan_site_id }}"
    'system_host_name': "{{ inventory_hostname}}"
    'system_system_ip': "{{ sdwan_system_ip }}"
    'banner_login': You are being monitored.
    'banner_motd': Welcome!
bootstrap_method: netconf
