viptela:
  system_ip: 1.1.100.2
  site_id: 100
  vbond:
    remote: 192.133.162.23
  model: 'vedge-CSR-1000v'
  personality: vedge
  uuid: 'CSR-DE49BFC4-10DF-8579-0F64-CD0F51603A38'
  template:
    name: 'dc-cedge'
    variables:
      'vpn512_interface': GigabitEthernet1
      'vpn0_interface': GigabitEthernet2
      'vpn0_internet_ipv4_address': 192.133.162.19/28
      'vpn0_default_gateway': 192.133.162.17
      'vpn10_interface': GigabitEthernet3
      'vpn10_ospf_interface': GigabitEthernet3  
      'vpn10_ipv4_address': 172.16.2.2/24
      'system_latitude': 35.856360
      'system_longitude': -78.879725
      'system_site_id': 100
      'system_host_name': "{{ inventory_hostname }}"
      'system_system_ip': 1.1.100.2
      'banner_login': "{{ login_banner }}"
      'banner_motd': "Welcome to {{ inventory_hostname }}!"
  gps_location:
    latitude: 35.856360
    longitude: -78.879725