# TODO  There's a lot of repeating code here, needs generalization/refactor

- import_playbook: clean-certs.yml
  tags: [control]

- import_playbook: remove-device.yml 
  vars: 
    passed: sdwan_edge
  tags: [edges]

- name: Delete Control Plane VMs
  hosts: localhost
  connection: local
  tags:
    - terraform
    - control
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Check for control.tfvars file
      stat:
        path: "{{ terraform_project_path[sdwan_control_infra]['control'] }}/{{ sdwan_control_infra }}_control.tfvars"
      register: control_stat_result

    - name: Terraform Destroy Control Plane
      terraform:
        project_path: "{{ terraform_project_path[sdwan_control_infra]['control'] }}"
        state: absent
        workspace: "{{ sdwan_control_infra }}_control"
        variables_file: "{{ sdwan_control_infra }}_control.tfvars"
      when: control_stat_result.stat.exists == true

- name: Delete Control Plane Network
  hosts: localhost
  connection: local
  tags:
    - terraform
    - network
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Check for network.tfvars file
      stat:
        path: "{{ terraform_project_path[sdwan_control_infra]['network'] }}/{{ sdwan_control_infra }}_network.tfvars"
      register: control_stat_result

    - name: Terraform Destroy Control Plane Network
      terraform:
        project_path: "{{ terraform_project_path[sdwan_control_infra]['network'] }}"
        state: absent
        workspace: "{{ sdwan_control_infra }}_network"
        variables_file: "{{ sdwan_control_infra }}_network.tfvars"
      when: control_stat_result.stat.exists == true

- name: Delete Edge VMs
  hosts: localhost
  connection: local
  tags:
    - terraform
    - edges
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Check for edges.tfvars file
      stat:
        path: "{{ terraform_project_path[sdwan_control_infra]['edges'] }}/{{ sdwan_control_infra }}_edges.tfvars"
      register: edges_stat_result

    - name: Terraform Destroy Edges
      terraform:
        project_path: "{{ terraform_project_path[sdwan_control_infra]['edges'] }}"
        state: absent
        workspace: "{{ sdwan_control_infra }}_edges"
        variables_file: edges.tfvars
      when: edges_stat_result.stat.exists == true

- name: Remove terraform state files
  hosts: localhost
  connection: local
  tags:
    - delete
    - never
  gather_facts: no
  tasks:
    - name: Delete control state
      file: 
        state: absent
        path: "{{ terraform_project_path[sdwan_control_infra]['control'] }}/terraform.tfstate.d/{{ sdwan_control_infra }}_control/terraform.tfstate"

    - name: Delete control network state
      file:
        state: absent
        path: "{{ terraform_project_path[sdwan_control_infra]['network'] }}/terraform.tfstate.d/{{ sdwan_control_infra }}_network/terraform.tfstate"

    - name: Delete edge state
      file:
        state: absent
        path: "{{ terraform_project_path[sdwan_control_infra]['edges'] }}/terraform.tfstate.d/{{ sdwan_control_infra }}_edges/terraform.tfstate"