- name: Configure vmanage
  hosts: localhost
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ansible.utils.ipaddr('address') }}"
    vbond_controller: "{{ groups.vbond_hosts[0] }}"
  tags:
    - control
    - vmanage
  any_errors_fatal: true
  gather_facts: no
  environment: "{{ proxy_env }}"
  tasks:
    - name: vManage Settings
      vmanage_settings:
        host: "{{ vmanage_ip }}"
        user: "{{ vmanage_user }}"
        password: "{{ vmanage_pass }}"
        organization: "{{ vmanage_org }}"
        vbond: "{{ sdwan_vbond }}"
      register: result
      retries: 30
      delay: 10
      until: result is not failed

    - name: Add Control Hosts
      vmanage_device:
        host: "{{ vmanage_ip }}"
        user: "{{ vmanage_user }}"
        password: "{{ vmanage_pass }}"
        device_username: "{{ hostvars[item].ansible_user }}"
        device_password: "{{ hostvars[item].ansible_password }}"
        name: "{{ item }}"
        personality: "{{ hostvars[item].sdwan_personality }}"
        transport_ip: "{{ hostvars[item].vpn0_ip | ansible.utils.ipaddr('address')}}"
      loop: "{{ groups.vbond_hosts + groups.vsmart_hosts }}"
      register: result
      retries: 10
      delay: 10
      until: result is not failed

    - debug:
        msg: "vManage IP: {{ vmanage_ip }}"

    - debug:
        msg: "vManage external IP: {{ sdwan_vmanage }}"
      when: sdwan_vmanage is defined
