- name: Import vManage Policy Lists
  hosts: localhost
  connection: local
  tags:
    - policy
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_mgmt_interface: "{{ hostvars[vmanage_host].mgmt_interface | default('ansible_host') }}"
    vmanage_ip: "{{ hostvars[vmanage_host][vmanage_mgmt_interface] | ipaddr('address') }}"
  gather_facts: no
  environment: "{{ proxy_env }}"
  tasks:
    - vmanage_policy_import:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        file: "{{ vmanage_policy_file }}"
      when: vmanage_templates_file is defined
