- name: Run terraform
  hosts: sdwan_edge
  connection: local
  any_errors_fatal: true
  vars:
    project_path: "{{ terraform_project_path[infra][sdwan_component] }}"
  tasks:
    - assert:
        that:
          - sdwan_component == "edge_network" or sdwan_component == "edges"
        msg: "sdwan_component must be set to either 'edge_network' or 'edges'"

    - name: Generate Terraform variables file
      template:
        src: "terraform/{{ infra }}_{{ sdwan_component }}_tfvars.j2"
        dest: "{{ project_path }}/{{ infra }}_{{ sdwan_component }}_{{ inventory_hostname }}.tfvars"
      tags: [tfvars, plan]
      when: not (sdwan_component == "edge_network" and infra == "vmware")

    - name: Terraform plan
      community.general.terraform:
        project_path: "{{ project_path }}"
        state: planned
        plan_file: "{{ infra }}_{{ sdwan_component }}_{{ inventory_hostname }}.tfplan"
        workspace: "{{ infra }}_{{ sdwan_component }}_{{ inventory_hostname }}"
        variables_file: "{{ infra }}_{{ sdwan_component }}_{{ inventory_hostname }}.tfvars"
        force_init: yes
      tags: [plan, apply]
      when: not (sdwan_component == "edge_network" and infra == "vmware")

    - name: Terraform apply
      community.general.terraform:
        project_path: "{{ project_path }}"
        state: present
        plan_file: "{{ infra }}_{{ sdwan_component }}_{{ inventory_hostname }}.tfplan"
        workspace: "{{ infra }}_{{ sdwan_component }}_{{ inventory_hostname }}"
        variables_file: "{{ infra }}_{{ sdwan_component }}_{{ inventory_hostname }}.tfvars"
      tags: apply
      when: not (sdwan_component == "edge_network" and infra == "vmware")
      register: outputs

    - name: Save VPC ID
      set_fact:
        sdwan_network: "{{ outputs.outputs.vpc_id.value }}"
        cacheable: yes
      when: sdwan_component == "edge_network" and infra == "aws"

    - debug:
        msg: "cEdge external IP: {{ outputs.outputs.cedge_transport_public_ip.value }}"
      when: sdwan_component == "edges" and (infra == "aws" or infra == "gcp")

    - debug:
        msg: "cEdge IP: {{ outputs.outputs.cedge_transport_ip.value }}"
      when: sdwan_component == "edges" and infra == "vmware"

    - meta: refresh_inventory
      tags: always
