- name: Run terraform
  hosts: localhost
  connection: local
  any_errors_fatal: true
  tasks:
    - assert:
        that:
          - sdwan_component == "network" or sdwan_component == "control"
        msg: "sdwan_component must be set to either 'network' or 'control'"

    - name: Generate Terraform variables file
      template:
        src: "terraform/{{ infra }}_{{ sdwan_component }}_tfvars.j2"
        dest: "{{ project_path }}/{{ infra }}_{{ sdwan_component }}.tfvars"
      tags: [tfvars, plan]
      when: sdwan_component is defined

    - name: Terraform plan
      terraform:
        project_path: "{{ project_path }}"
        state: planned
        plan_file: "{{ infra }}_{{ sdwan_component }}.tfplan"
        workspace: "{{ infra }}_{{ sdwan_component }}"
        variables_file: "{{ infra }}_{{ sdwan_component }}.tfvars"
        force_init: yes
      tags: [plan, apply]
      when: sdwan_component is defined

    - name: Terraform apply
      terraform:
        project_path: "{{ lookup('env', 'PROJ_ROOT') }}{{ project_path }}"
        state: present
        plan_file: "{{ infra }}_{{ sdwan_component }}.tfplan"
        workspace: "{{ infra }}_{{ sdwan_component }}"
        variables_file: "{{ infra }}_{{ sdwan_component }}.tfvars"
      tags: apply
      when: sdwan_component is defined
      register: outputs

    - name: Set proxy IP
      set_fact:
        proxy_env:
          https_proxy: "http://{{ outputs.outputs.devbox_public_ip.value }}:8443"
        cacheable: yes
      when: sdwan_component == "network"

    - debug:
        var: proxy_env
      when: sdwan_component == "network"

    - name: Set vManage/vBond external IP
      set_fact:
        sdwan_vmanage: "{{ outputs.outputs.vmanages_vmanageEth1EIP.value[0] }}"
        sdwan_vbond: "{{ outputs.outputs.vbonds_vbondEth1EIP.value[0] }}"
        cacheable: yes
      when: sdwan_component == "control" and infra == "aws"

    - debug:
        msg: "vManage external IP: {{ sdwan_vmanage }}\nvBond external IP: {{ sdwan_vbond }}"
      when: sdwan_component == "control" and infra == "aws"

    - meta: refresh_inventory
      tags: always
        