vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: ge0/0
        ip:
          address: 192.133.162.23/28
        tunnel_interface:
          allow_service:
            - all
        enabled: yes
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 192.133.162.17