---
global_config:
  common_tags:
    Owner: "Owner Name"
    Project: "Project Name"
    Automation: "sdwan-devops"
  ubuntu_image: "ubuntu-22-04"
  # ssh_public_key_file: "{home_dir}/.ssh/id_rsa.pub"
  ssh_public_key: "<your public key>"

infra_providers:
  aws:
    ntp_server: "169.254.169.123"
  gcp:
    ntp_server: "metadata.google.internal"
    project: "gcp-sdwaniac-nprd-84677"
  azure:
    ntp_server: "pool.ntp.org"
  vmware:
    ntp_server: "pool.ntp.org"
    vsphere_server: ""
    vsphere_user: ""
    vsphere_password: ""


controllers:
  infra:
    provider: "aws"
    region: "us-east-1"
  # dns_domain: "acme.com"
    sw_version: "20.12.1"
    cloud_init_format: v2
  config:
    organization_name: "Cisco DevOps"
    site_id: 1
    acl_ingress_ipv4: [ "0.0.0.0/1", "128.0.0.0/1" ]
    acl_ingress_ipv6: [ "::/0" ]
    cidr: "10.128.0.0/22"
    vpn0_gateway: "10.128.1.1"
  certificate_authority:
    cert_dir: '/ansible/myCA'
  vmanage:
    infra:
      image_id: "ami-02b3d4da3fc136dab"
      instance_type: "c5.4xlarge"
    config:
      username: "admin"
      password: "C1sco12345"
      system_ip: "1.1.1.1"
      vpn0_interface_ipv4: "10.128.1.11/24"
  vbond:
    infra:
      image_id: "ami-05ea2898dccbd19bc"
      instance_type: "c5.large"
    config:
      system_ip: "1.1.1.2"
      vpn0_interface_ipv4: "10.128.1.12/24"
  vsmart:
    infra:
      image_id: "ami-08a51380a937e415f"
      instance_type: "c5.large"
    config:
      system_ip: "1.1.1.3"
      vpn0_interface_ipv4: "10.128.1.13/24"

wan_edges:
  cedge-aws:
    infra:
      provider: "aws"
      region: "us-east-1"
      image_id: "ami-09db869a0fe05bd4e"
      instance_type: "c5n.large"
      sw_version: "17.08.01a"
      sdwan_model: vedge-C8000V
      sdwan_uuid: "C8K-F6A3B082-EDDB-BA43-93DB-2AA42DFE58DB"
    config:
      site_id: 101
      system_ip: "1.1.1.4"
      cidr: "10.128.4.0/23"
  cedge-gcp:
    infra:
      provider: "gcp"
      region: "us-central1"
      zone: "us-central1-a"
      image_id: "cisco-public/cisco-c8k-17-08-01a"
      instance_type: "n1-standard-4"
      sw_version: "17.08.01a"
      sdwan_model: vedge-C8000V
      sdwan_uuid: "C8K-6DF43510-2590-5146-3AAA-EEF129DAC175"
    config:
      site_id: 102
      system_ip: "1.1.1.5"
      cidr: "10.128.6.0/23"
  cedge-azure:
    infra:
      provider: "azure"
      region: "northcentralus"
      image_id: "17_08_01a-byol"
      instance_type: "Standard_DS1_v2"
      sw_version: "17.08.01a"
      sdwan_model: vedge-C8000V
      sdwan_uuid: "C8K-0EEBC36C-18EC-2FF6-40F4-A9DEC1BBB25D"
    config:
      site_id: 103
      system_ip: "1.1.1.6"
      cidr: "10.128.8.0/23"
  cedge-dc:
    infra:
      provider: "vmware"
      image_id: "c8000v-17.08.01a"
      sw_version: "17.08.01a"
      sdwan_model: vedge-C8000V
      sdwan_uuid: "C8K-B63650AB-5DB8-BAC8-2A63-D32EA7676FC2"
      vmware:
        datacenter: ""
        cluster: ""
        datastore: ""
        folder: ""
        vpn0_portgroup: "VM Network"
        vpn512_portgroup: "VM Network"
        servicevpn_portgroup: "VM Network"
    config:
      site_id: 104
      system_ip: "1.1.1.7"
      vpn0_range: "22.1.140.0/24"
      vpn1_range: "22.1.11.0/24"
      vpn0_interface_ipv4: "22.1.140.100/24"

...
