sdwan_system_ip: 192.168.255.15
sdwan_site_id: 3
sdwan_vbond: 10.0.0.11
sdwan_model: 'vedge-cloud'
sdwan_personality: vedge
sdwan_uuid: '36b8fb11-0aa4-8f2e-5174-a7793ae246f4'
sdwan_template:
  name: 'branch-vedge-cloud'
  variables:
    'vpn512_interface': eth0
    'vpn0_interface': ge0/0    
    'vpn0_internet_ipv4_address': 172.20.0.14/30
    'vpn0_default_gateway': 172.20.0.13
    'vpn1_interface': ge0/1
    'vpn1_ipv4_address': 192.168.2.1/24
    'system_latitude': 32.999892
    'system_longitude': -96.678886
    'system_site_id': 3
    'system_host_name': site2-vedge1
    'system_system_ip': 192.168.255.15
    'banner_login': "{{ login_banner }}"
    'banner_motd': Welcome to site2-vedge1!
sdwan_gps_location:
  latitude: 32.999892
  longitude: -96.678886