---
platform: linux

image_resource:
  type: docker-image
  source: {repository: sconrod/netmiko}

inputs:
  - name: input

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  REGION: ((aws.region))
  NAME: ((az.name))
  VAULT_ADDR: ((vault.addr))
  SSH_TOKEN: ((ssh-token.token))
run:
  path: /bin/sh
  args: ["./input/configure_vmanage.sh"]

