sdwan_system_ip: 1.1.10.1
sdwan_transport_ip: 192.133.179.16
ansible_host: "{{ sdwan_transport_ip }}"
sdwan_site_id: 10
sdwan_model: 'vedge-cloud'
sdwan_uuid: b1b0c97d-acd9-6df5-19d5-6d8a9923fbfb
sdwan_personality: vedge
sdwan_template:
  name: 'branch-vedge-cloud'
  variables:
    'vpn512_interface': eth0
    'vpn0_interface': ge0/0
    'vpn0_internet_ipv4_address': 192.133.179.16/24
    'vpn0_default_gateway': 192.133.179.1
    'vpn1_interface': ge0/1
    'vpn1_ipv4_address': 192.168.10.1/24
    'system_latitude': 37.411343
    'system_longitude': -121.938803
    'system_site_id': "{{ sdwan_site_id }}"
    'system_host_name': "{{ inventory_hostname}}"
    'system_system_ip': "{{ sdwan_system_ip }}"
    'banner_login': You are being monitored.
    'banner_motd': Welcome!
bootstrap_method: netconf
