viptela:
  system_ip: 192.168.255.10
  transport_ip: 10.0.0.10
  org: "{{ organization_name }}"
  site_id: 1
  vbond:
    remote: 10.0.0.11
  gps_location:
    latitude: 37.411343
    longitude: -121.938803

vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1
        ip:
          address: 10.0.0.10/24
        tunnel_interface:
        enabled: true
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.0.0.1