viptela:
  system_ip: 192.168.255.11
  transport_ip: 10.0.0.11
  site_id: 1
  vbond:
    remote: 10.0.0.11
    local: true
  personality: vbond
  gps_location:
    latitude: 37.411343
    longitude: -121.938803

vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: ge0/0
        ip:
          address: 10.0.0.11/24
        tunnel_interface:
          allow_service:
            - netconf
        enabled: yes
        allow_service:
          - all
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.0.0.1