sdwan_system_ip: 1.1.5.1
sdwan_transport_ip: 192.133.179.15
vpn0_netmask: 24
vpn0_gateway: 192.133.179.1
ansible_host: "{{ sdwan_transport_ip }}"
sdwan_site_id: 5
sdwan_template:
  name: 'vsmart'
  variables:
    'vpn0_internet_ipv4_address': "{{ sdwan_transport_ip }}/{{ vpn0_netmask }}"
    'vpn0_default_gateway': "{{ vpn0_gateway }}"
    'system_site_id': "{{ sdwan_site_id }}"
    'system_host_name': "{{ inventory_hostname}}"
    'system_system_ip': "{{ sdwan_system_ip }}"