- name: Run the ping
  ios_ping:
    source: "{{ ping_src_ip }}"
    dest: "{{ ping_dst_ip }}"
    vrf: "{{ ping_vpn }}"
    state: "{{ 'present' if ping_pass else 'absent' }}"
  register: ping
  vars:
    ansible_user: "{{ hostvars[ping_vedge].ansible_user }}"
    ansible_password: "{{ hostvars[ping_vedge].ansible_password }}"
    ansible_network_os: ios
  delegate_to: "{{ hostvars[ping_vedge].ansible_host }}"
  connection: network_cli

- name: Record results
  set_fact:
    ping_rx: "{{ ping.packets_rx }}"
    ping_tx: "{{ ping.packets_tx }}"
    ping_loss: "{{ ping.packet_loss }}"
    ping_rtt_min: "{{ ping.rtt.min | default(0, true)}}"
    ping_rtt_max: "{{ ping.rtt.max | default(0, true)}}"
    ping_rtt_avg: "{{ ping.rtt.avg | default(0, true)}}"