jobs:
- name: lab-prep
  plan:
  - get: git-git-git-cisco-sdwan-devops
    trigger: true
  - get: git-cisco-terraform-sdwan
    trigger: true
  - config:
      image_resource:
        name: ""
        source:
          repository: sconrod/python-aws-image
          tag: 2
        type: docker-image
      inputs:
      - name: cisco-sdwan-devops
      - name: cisco-terraform-sdwan
      platform: linux
      run:
        path: sh
        args:
          - -ce
          - |
            export AWS_PAGER=""
            export Name=$NAME
            echo $NAME
            aws configure set aws_access_key_id $AWS_KEY_ID
            aws configure set aws_secret_access_key $AWS_KEY
            aws configure set default.region $REGION
            aws sts get-caller-identity --query Account --output text
            echo "WELCOME TO THE CISCO SDWAN AUTOMATION LAB FOR DEVOPS/NETOPS ENGINEERS"
    task: check-aws
    params:
      AWS_KEY_ID: ((Access_key_ID.Access_key))
      AWS_KEY: ((Secret_access_key.Secret_access_key))
      REGION: ((aws.region))
      NAME: ((az.name))
      VAULT_ADDR: ((vault.addr))

- name: deploy-aws-env
  plan:
    - get: git-git-git-cisco-sdwan-devops
    - get: git-cisco-terraform-sdwan
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/python-aws-image
            tag: 2
          type: docker-image
        inputs:
          - name: git-git-git-cisco-sdwan-devops
          - name: git-cisco-terraform-sdwan
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              echo "Working Directory is......"
              pwd
              echo "The contents of the working directory is..."
              ls -la
              export AWS_PAGER=""
              export NAME=$NAME
              echo $NAME
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              chmod a+x git-git-git-cisco-sdwan-devops/concourse/ansible.sh
              ./git-git-git-cisco-sdwan-devops/concourse/ansible.sh

      task: build-vpc
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))
        NAME: ((az.name))
        VAULT_ADDR: ((vault.addr))
        SSH_TOKEN: ((ssh-token.token))

resource_types:
resources:
  - name: git-git-git-cisco-sdwan-devops
    source:
      Username: ((Username))
      branch: concourse
      email: ((email))
      private_key: ((private_key))
      uri: git@github.com:CiscoDevNet/terraform-sdwan.git
    type: git

  - name: git-cisco-terraform-sdwan
    source:
      Username: ((Username))
      branch: cloud
      email: ((email))
      private_key: ((private_key))
      uri: git@github.com:CiscoDevNet/terraform-sdwan.git
    type: git