jobs:
- name: lab-prep
  plan:
  - get: sdwan-devops
    trigger: true
  - get: terraform-sdwan
    trigger: true
  - config:
      image_resource:
        name: ""
        source:
          repository: sconrod/sdwan-ubuntu
          tag: 1.0
        type: docker-image
      inputs:
      - name: sdwan-devops
      - name: terraform-sdwan
      platform: linux
      run:
        path: sh
        args:
          - -ce
          - |
            export AWS_PAGER=""
            export Name=$NAME
            echo $NAME
            aws configure set aws_access_key_id $AWS_KEY_ID
            aws configure set aws_secret_access_key $AWS_KEY
            aws configure set default.region $REGION
            aws sts get-caller-identity --query Account --output text
            echo "WELCOME TO THE CISCO SDWAN AUTOMATION LAB FOR DEVOPS/NETOPS ENGINEERS"
    task: check-aws
    params:
      AWS_KEY_ID: ((Access_key_ID.Access_key))
      AWS_KEY: ((Secret_access_key.Secret_access_key))
      REGION: ((aws.region))
      NAME: ((az.name))
      VAULT_ADDR: ((vault.addr))

- name: deploy-aws-key
  plan:
    - get: sdwan-devops
    - get: terraform-sdwan
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/sdwan-ubuntu
            tag: 1.0
          type: docker-image
        inputs:
          - name: sdwan-devops
          - name: terraform-sdwan
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              export AWS_PAGER=""
              export NAME=$NAME
              echo $NAME
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              cd sdwan-devops/concourse
              chmod a+x aws_key_vault.sh
              ./aws_key_vault.sh

      task: deploy-aws-key
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))
        NAME: ((az.name))
        VAULT_ADDR: ((vault.addr))
        SSH_TOKEN: ((ssh-token.token))

- name: deploy-aws-vpc
  plan:
    - get: sdwan-devops
    - get: terraform-sdwan
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/sdwan-ubuntu
            tag: 1.0
          type: docker-image
        inputs:
          - name: sdwan-devops
          - name: terraform-sdwan
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              export AWS_PAGER=""
              export NAME=$NAME
              echo $NAME
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              cd sdwan-devops/concourse
              chmod a+x aws_deploy_sdwan.sh
              ./aws_deploy_sdwan.sh
      task: build-vpc
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))
        NAME: ((az.name))
        VAULT_ADDR: ((vault.addr))
        SSH_TOKEN: ((ssh-token.token))

- name: deploy-aws-instances
  plan:
    - get: sdwan-devops
    - get: terraform-sdwan
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/sdwan-ubuntu
            tag: 1.0
          type: docker-image
        inputs:
          - name: sdwan-devops
          - name: terraform-sdwan
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              export AWS_PAGER=""
              export NAME=$NAME
              echo $NAME
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              cd sdwan-devops/concourse
              chmod a+x deploy_instances.sh
              ./deploy_instances.sh
      task: build-instances
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))
        NAME: ((az.name))
        VAULT_ADDR: ((vault.addr))
        SSH_TOKEN: ((ssh-token.token))

- name: deploy-aws-vmanage
  plan:
    - get: sdwan-devops
    - get: terraform-sdwan
    - config:
        image_resource:
          name: ""
          source:
            repository: sconrod/sdwan-ubuntu
            tag: 1.0
          type: docker-image
        inputs:
          - name: sdwan-devops
          - name: terraform-sdwan
        platform: linux
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              export AWS_PAGER=""
              export NAME=$NAME
              echo $NAME
              aws configure set aws_access_key_id $AWS_KEY_ID
              aws configure set aws_secret_access_key $AWS_KEY
              aws configure set default.region $REGION
              aws sts get-caller-identity --query Account --output text
              export AWS_PAGER=""
              cd sdwan-devops/concourse
              chmod a+x deploy_vmanage.sh
              ./deploy_vmanage.sh
      task: build-instances
      params:
        AWS_KEY_ID: ((Access_key_ID.Access_key))
        AWS_KEY: ((Secret_access_key.Secret_access_key))
        REGION: ((aws.region))
        NAME: ((az.name))
        VAULT_ADDR: ((vault.addr))
        SSH_TOKEN: ((ssh-token.token))

resource_types:
resources:
  - name: sdwan-devops
    source:
      Username: ((Username))
      branch: cloud-concourse
      email: ((email))
      private_key: ((private_key))
      uri: git@github.com:CiscoDevNet/sdwan-devops.git
    type: git

  - name: terraform-sdwan
    source:
      Username: ((Username))
      branch: cloud-concourse
      email: ((email))
      private_key: ((private_key))
      uri: git@github.com:CiscoDevNet/terraform-sdwan.git
    type: git