vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1
        ip:
          address: 10.0.0.10/24
        tunnel_interface:
        enabled: true
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.0.0.1