- vmanage_nping:
    user: "{{ vmanage_user }}"
    host: "{{ vmanage_ip }}"
    password: "{{ vmanage_pass }}"
    dst_ip: "{{ ping_dst_ip }}"
    vedge: "{{ ping_vedge }}"
    vpn: "{{ ping_vpn }}"
    count: "{{ ping_count | default(5) }}"
    rapid: no
  register: nping
  delegate_to: localhost

- set_fact:
    ping_tx: "{{ nping.json.packetsTransmitted }}"
    # ping_rx: "{{ nping.json.packetsReceived }}"
    ping_rx: "{{ nping.json.rawOutput | select('search', 'Echo reply') | list | length | default('0') }}"
    ping_loss: "{{ nping.json.lossPercentage }}"
    ping_rtt_min: "{{ nping.json.minRoundTrip }}"
    ping_rtt_max: "{{ nping.json.maxRoundTrip }}"
    ping_rtt_avg: "{{ nping.json.avgRoundTrip }}"


- set_fact:
    ping_loss: "{{ (100 - (100 * (ping_rx|int / ping_tx|int))) | int | string }}%"
  