- set_fact:
    edge_type: "{{ 'vedge' if hostvars[ping_vedge].sdwan_model is regex('^vedge-[c0-9]') else 'cedge' }}"

- include_tasks:
    file: "ping-{{ edge_type }}.yml"

- debug:
    msg: "{{ ping_vedge }}(VPN {{ping_vpn}}) => {{ ping_dst_ip }}: {{ ping_rx }}/{{ ping_tx }}, {{ ping_loss }} loss, Pass(actual/expected) {{ actual_result }}/{{ expected_result }}"
  failed_when: actual_result != expected_result
  ignore_errors: False
  vars:
    actual_result: "{{ True if ping_loss != '100%' else False }}"
    expected_result: "{{ ping_pass }}"
