- ios_ping:
    provider:
      host: "{{ hostvars[ping_vedge].ansible_host }}"
      username: admin
      password: admin
    source: "{{ ping_src_ip }}"
    dest: "{{ ping_dst_ip }}"
    vrf: "{{ ping_vpn }}"
    state: "{{ 'present' if ping_pass else 'absent' }}"
  connection: network_cli
  delegate_to: localhost
  register: ping

- set_fact:
    ping_rx: "{{ ping.packets_rx }}"
    ping_tx: "{{ ping.packets_tx }}"
    ping_loss: "{{ ping.packet_loss }}"
    ping_rtt_min: "{{ ping.rtt.min }}"
    ping_rtt_max: "{{ ping.rtt.max }}"
    ping_rtt_avg: "{{ ping.rtt.avg }}"