vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1
        ip:
          address: 10.0.0.12/24
        tunnel_interface:
          allow_service:
            - netconf
        enabled: yes
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.0.0.1