#TODO trim to basics
#TODO does this actually work? The variables should have TF_VAR_. Where do these variables come from?
vmanage_user: "{{ lookup('env','VMANAGE_USERNAME') }}"
vmanage_pass: "{{ lookup('env','VMANAGE_PASS') }}"
# default is "cisco" encrypted, 20.5 and above don't allow plaintext passwords
viptela_encrypted_pass: "{{ lookup('env','VMANAGE_ENCRYPTED_PASS') }}"
vmanage_org: "{{ lookup('env','VMANAGE_ORG') | default('', true) }}"
smart_token: "{{ lookup('env','SMART_TOKEN') | default('', true) }}"
ansible_user: "{{ vmanage_user }}"
ansible_password: "{{ vmanage_pass }}"
ssh_pubkey: "{{ lookup('env','SSH_PUBKEY_BASE64') | b64decode | trim }}"
ssh_pubkey_fp: "{{ lookup('env','SSH_PUBKEY_FP_BASE64') | b64decode | trim }}"
#TODO move definition of these files location to env script
sdwan_serial_file: "/ansible/licenses/serialFile.viptela"
sdwan_cert_dir: "/ansible/myCA"

sdwan_control_infra: "{{ lookup('env','SDWAN_CONTROL_INFRA') | default('vmware', true)}}"
sdwan_datacenter: "{{ lookup('env', 'SDWAN_DATACENTER') }}"
sdwan_datacenter_zone: "{{ sdwan_datacenter }}-c"
sdwan_cidr: "{{ lookup('env', 'NETWORK_CIDR') }}"
acl_cidr_blocks: "{{ lookup('env', 'ACL_RANGES_IPV4_BASE64') | b64decode | trim }}"
acl6_cidr_blocks: "{{ lookup('env', 'ACL_RANGES_IPV6_BASE64') | b64decode | trim }}"

vbond_vpn0_ipv4: "{{ lookup('env','VBOND1_IP') }}"

cloudinit_type: "{{ lookup('env','CLOUDINIT_TYPE') | default('v1')}}"
viptela_version: "{{ lookup('env','VIPTELA_VERSION') | default('20.8.1', true) }}"
iosxe_sdwan_image: "{{ lookup('env','IOSXE_SDWAN_IMAGE') | default('iosxe-sdwan-16.12.2r', true) }}"
csr1000v_image: "{{ lookup('env','CSR1000V_IMAGE') | default('csr1000v-16.12.02r', true) }}"
ubuntu_image: "{{ lookup('env','UBUNTU_IMAGE') | default('ubuntu-22-04', true) }}"
# TODO Encrypt/Vault this in real life
sdwan_ca_passphrase: "{{ lookup('env','SDWAN_CA_PASSPHRASE') }}"
sdwan_ca_cert: "{{ sdwan_cert_dir }}/myCA.pem"
# VMware
vmware_vmanage_template: "viptela-manage-{{ viptela_version }}"
vmware_vsmart_template: "viptela-smart-{{ viptela_version }}"
vmware_vbond_template: "viptela-edge-{{ viptela_version }}"
vmware_vedge_template: "viptela-edge-{{ viptela_version }}"
vmware_cedge_template: "{{ iosxe_sdwan_image }}"
vsphere_server: "{{ lookup('env','TF_VAR_vsphere_server') }}"
vsphere_user: "{{ lookup('env','TF_VAR_vsphere_user') | default('administrator@vsphere.local', true) }}"
vsphere_password: "{{ lookup('env','TF_VAR_vsphere_password') }}"
datacenter: "{{ lookup('env','TF_VAR_datacenter') }}"
cluster: "{{ lookup('env','TF_VAR_cluster') }}"
datastore: "{{ lookup('env','TF_VAR_datastore') }}"
folder: "{{ lookup('env','TF_VAR_folder') | default('', true) }}"
# AWS
aws_vmanage_ami: "{{ lookup('env','VMANAGE_AMI') }}"
aws_vbond_ami: "{{ lookup('env','VBOND_AMI') }}"
aws_vsmart_ami: "{{ lookup('env','VSMART_AMI') }}"
aws_cedge_ami: "{{ lookup('env','CEDGE_AMI') }}"
aws_vmanage_instance_type: "{{ lookup('env','VMANAGE_INSTANCE_TYPE') | default('c5.4xlarge', true) }}"
aws_vbond_instance_type: "{{ lookup('env','VBOND_INSTANCE_TYPE') | default('c5.large', true) }}"
aws_vsmart_instance_type: "{{ lookup('env','VSMART_INSTANCE_TYPE') | default('c5.large', true) }}"
aws_cedge_instance_type: "{{ lookup('env', 'CEDGE_AWS_INSTANCE_TYPE')  | default('c5n.large', true) }}"
aws_ntp_server: "169.254.169.123"
aws_route53_zone: "{{ lookup('env','DNS_DOMAIN') }}"
# GCP
gcp_project: "{{ lookup('env','GCP_PROJECT') }}"
gcp_cedge_image_id: "{{ lookup('env','CEDGE_GCP_IMAGE_ID') }}"
gcp_cedge_instance_type: "{{ lookup('env', 'CEDGE_GCP_INSTANCE_TYPE')  | default('n1-standard-4', true) }}"
# Azure
azure_cedge_image_id: "{{ lookup('env','CEDGE_AZURE_IMAGE_ID') }}"
azure_cedge_instance_type: "{{ lookup('env', 'CEDGE_AZURE_INSTANCE_TYPE')  | default('Standard_DS1_v2', true) }}"
