sdwan_system_ip: 192.168.255.10
sdwan_transport_ip: 10.0.0.10
sdwan_org: "{{ organization_name }}"
sdwan_site_id: 1
sdwan_vbond: 10.0.0.11
sdwan_personality: vmanage
sdwan_device_model: vmanage
sdwan_gps_location:
  latitude: 37.411343
  longitude: -121.938803
