---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/sdwan-ubuntu
    tag: 1.0

inputs:
  - name: git-resource
params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  REGION: us-west-2
  NAME: us-west-2a
  VAULT_ADDR: http://prod-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -ce
    - |
      export AWS_PAGER=""
      export Name=$NAME
      echo $NAME
      aws configure set aws_access_key_id $AWS_KEY_ID
      aws configure set aws_secret_access_key $AWS_KEY
      aws configure set default.region $REGION
      aws sts get-caller-identity --query Account --output text
      pwd
      ls -la
      chmod a+x git-resource/tasks/aws_deploy/aws_config_vmanage.sh
      ./git-resource/tasks/aws_deploy/aws_config_vmanage.sh



      