---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2

inputs:
  - name: git-resource

params:
  VAULT_ADDR: http://dev-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -ce
    - |
      chmod a+x git-resource/tasks/aws_deploy/vault_prep.sh
      ./git-resource/tasks/aws_deploy/vault_prep.sh


      