---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2

inputs:
  - name: sdwan-devops

params:
  VAULT_ADDR: http://vault.cisco-sdwan-labs.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -ce
    - |
      chmod a+x cisco-sdwan-devops/tasks/python/aws_deploy/vault_prep.sh
      ./sdwan-devops/tasks/python/aws_deploy/vault_prep.sh


      