---
name: CI
on:
  pull_request:
    branches:
      - master
    workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    env:
      TF_VAR_vsphere_user: administrator@ciscops.net
      TF_VAR_vsphere_password: \&@xda5YFMexa5Eh4
      TF_VAR_vsphere_server: cpn-rtp-vc1.ciscops.net
      TF_VAR_folder: sdwan-devops-ci
      TF_VAR_cluster: cpn-rtp-hx2
      TF_VAR_datacenter: RTP
      TF_VAR_datastore: cpn-rtp-hx2-colab1
      TF_VAR_iso_datastore: cpn-rtp-hx2-colab1
      TF_VAR_iso_path: cloud-init
      VMANAGE_ORG: CIDR_SDWAN_WORKSHOPS
      VIPTELA_VERSION: 20.7.1
      CLOUDINIT_TYPE: v2
      VMANAGE1_IP: 192.133.184.29/22
      VSMART1_IP: 192.133.184.30/22
      VBOND1_IP: 192.133.184.31/22
      HQ_EDGE1_IP: 192.133.184.32/22
      SITE1_EDGE1_IP: 192.133.184.33/22
      SITE2_EDGE1_IP: 192.133.184.34/22
      VPN0_GATEWAY: 192.133.184.1
      VPN0_PORTGROUP: cpn-rtp-colab4
      VPN512_PORTGROUP: cpn-rtp-colab4
      SERVICEVPN_PORTGROUP: cpn-rtp-colab4
      IOSXE_SDWAN_IMAGE: csr1000v-16.12.02r
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v2
      - name: Install PIP requirements
        run: pip install -r requirements.txt
      - name: Clean Existing Deployment
        run: ansible-playbook clean-vmware.yml
      - name: Build CA
        run: ansible-playbook build-ca.yml
      - name: Build VMware
        run: ansible-playbook build-vmware.yml
      - name: Configure Control Plane
        run: ansible-playbook config-vmware.yml
      - name: Deploy Edges
        run: ansible-playbook deploy-vmware.yml
      - name: Wait for Edges to Sync
        run: ansible-playbook waitfor-sync.yml
      - name: Check SD-WAN
        run: ansible-playbook check-sdwan.yml
      - name: Cleanup
        run: ansible-playbook clean-vmware.yml